ruby_probando/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :estadisticas
  resources :articles
  get 'welcome/index'

  resources :articles

  root 'welcome#index'

end

ruby_probando/app/models/article.rb
class Article < ActiveRecord::Base
end

ruby_probando/app/models/estadistica.rb
class Estadistica < ActiveRecord::Base
	belongs_to :user
end

ruby_probando/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :estadisica
end

ruby_probando/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:titulo, :cuerpo, :contador_visitas)
    end
end

ruby_probando/app/controllers/estadisticas_controller.rb
class EstadisticasController < ApplicationController
  before_action :set_estadistica, only: [:show, :edit, :update, :destroy]

  # GET /estadisticas
  # GET /estadisticas.json
  def index
    @estadisticas = Estadistica.all
  end

  # GET /estadisticas/1
  # GET /estadisticas/1.json
  def show
  end

  # GET /estadisticas/new
  def new
    @estadistica = Estadistica.new
  end

  # GET /estadisticas/1/edit
  def edit
  end

  # POST /estadisticas
  # POST /estadisticas.json
  def create
    @estadistica = Estadistica.new(estadistica_params)

    respond_to do |format|
      if @estadistica.save
        format.html { redirect_to @estadistica, notice: 'Estadistica was successfully created.' }
        format.json { render :show, status: :created, location: @estadistica }
      else
        format.html { render :new }
        format.json { render json: @estadistica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estadisticas/1
  # PATCH/PUT /estadisticas/1.json
  def update
    respond_to do |format|
      if @estadistica.update(estadistica_params)
        format.html { redirect_to @estadistica, notice: 'Estadistica was successfully updated.' }
        format.json { render :show, status: :ok, location: @estadistica }
      else
        format.html { render :edit }
        format.json { render json: @estadistica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estadisticas/1
  # DELETE /estadisticas/1.json
  def destroy
    @estadistica.destroy
    respond_to do |format|
      format.html { redirect_to estadisticas_url, notice: 'Estadistica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estadistica
      @estadistica = Estadistica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estadistica_params
      params.require(:estadistica).permit(:clasificacion, :victorias, :derrotas, :empates)
    end
end

ruby_probando/app/helpers/articles_helper.rb
module ArticlesHelper
end

ruby_probando/app/helpers/estadisticas_helper.rb
module EstadisticasHelper
end

ruby_probando/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :titulo, placeholder: "Título",class:"form-control"%>
  </div>

  <div class="field">
    <%= f.text_area :cuerpo , placeholder: "Escribe aquí el artículo",style:"height:250px", class:"form-control"%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

ruby_probando/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

ruby_probando/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th>Contador visitas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.titulo %></td>
        <td><%= article.cuerpo %></td>
        <td><%= article.contador_visitas %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

ruby_probando/app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
<h1>Nuevo Articulo</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</div>

ruby_probando/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @article.titulo %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @article.cuerpo %>
</p>

<p>
  <strong>Contador visitas:</strong>
  <%= @article.contador_visitas %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

ruby_probando/app/views/estadisticas/_form.html.erb
<%= form_for(@estadistica) do |f| %>
  <% if @estadistica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estadistica.errors.count, "error") %> prohibited this estadistica from being saved:</h2>

      <ul>
      <% @estadistica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :clasificacion %><br>
    <%= f.number_field :clasificacion %>
  </div>
  <div class="field">
    <%= f.label :victorias %><br>
    <%= f.number_field :victorias %>
  </div>
  <div class="field">
    <%= f.label :derrotas %><br>
    <%= f.number_field :derrotas %>
  </div>
  <div class="field">
    <%= f.label :empates %><br>
    <%= f.number_field :empates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby_probando/app/views/estadisticas/edit.html.erb
<h1>Editing Estadistica</h1>

<%= render 'form' %>

<%= link_to 'Show', @estadistica %> |
<%= link_to 'Back', estadisticas_path %>

ruby_probando/app/views/estadisticas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Estadisticas</h1>

<table>
  <thead>
    <tr>
      <th>Clasificacion</th>
      <th>Victorias</th>
      <th>Derrotas</th>
      <th>Empates</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estadisticas.each do |estadistica| %>
      <tr>
        <td><%= estadistica.clasificacion %></td>
        <td><%= estadistica.victorias %></td>
        <td><%= estadistica.derrotas %></td>
        <td><%= estadistica.empates %></td>
        <td><%= link_to 'Show', estadistica %></td>
        <td><%= link_to 'Edit', edit_estadistica_path(estadistica) %></td>
        <td><%= link_to 'Destroy', estadistica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estadistica', new_estadistica_path %>

ruby_probando/app/views/estadisticas/new.html.erb
<h1>New Estadistica</h1>

<%= render 'form' %>

<%= link_to 'Back', estadisticas_path %>

ruby_probando/app/views/estadisticas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clasificacion:</strong>
  <%= @estadistica.clasificacion %>
</p>

<p>
  <strong>Victorias:</strong>
  <%= @estadistica.victorias %>
</p>

<p>
  <strong>Derrotas:</strong>
  <%= @estadistica.derrotas %>
</p>

<p>
  <strong>Empates:</strong>
  <%= @estadistica.empates %>
</p>

<%= link_to 'Edit', edit_estadistica_path(@estadistica) %> |
<%= link_to 'Back', estadisticas_path %>

ruby_probando/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Probando weas</title>
  	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track'  => true %>
	<%= javascript_include_tag 'application','data-turbolinks-track'  =>true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<header>
		<nav class="be-blue white large-padding">
			<url class="no-list row center-xs middle-xs">
				<li class="col-md">
					<h1 class="no-margin " id="logo">Blog Economia</h1>
				</li>
				<li class="col-md">
					<%= link_to "Inicio", root_path %>
				</li>
				<li class="col-md">
					<%= link_to "Articulos", articles_path %>
				</li>
				<li class="col-md">
					<%= link_to "Tecnologia", root_path %>
				</li>
				<li class="col-md">
					<%= link_to "Antecedentes", root_path %>
				</li>
			</url>
		</nav>	
	</header>

<%= yield %>

<div id="footer">
<div id="container">
<p>contenido pie de página </p>	
</div>

</div>
</body>
</html>

ruby_probando/app/views/welcome/index.html.erb
<h1> Hola mundo!</h1>