distribuidos/config/routes.rb
Rails.application.routes.draw do
  get 'descargas/index'

  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'welcome/index'

  root 'welcome#index'

end

distribuidos/app/models/enfrentamiento.rb
class Enfrentamiento < ActiveRecord::Base
	belongs_to :user
end

distribuidos/app/models/estadistica.rb
class Estadistica < ActiveRecord::Base
	belongs_to :user
	validates :user_id, uniqueness: {case_sensitive: false ,message: " El usuario no se registró"}
end

distribuidos/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :estadisica
  has_many :enfrentamiento


  validates :user_name, uniqueness: {case_sensitive: false,message: " El nombre de usuario ya esta registrado"}
  validate :confirmacion
  def confirmacion
  	if (self.password != self.pass)
  		errors.add(:pass,"")
  		errors.add(:password,"Las contraseñas, no coinciden")
  	end	
  end
end

distribuidos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name,:email,:password,:pass])
        end
end

distribuidos/app/controllers/descargas_controller.rb
class DescargasController < ApplicationController
  def index
  end
end

distribuidos/app/controllers/estadistica_controller.rb
class EstadisticaController < ApplicationController
end

distribuidos/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

distribuidos/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

distribuidos/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

distribuidos/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

    #def new
    #  @user=User.new();
    #end

    def create
    #  @nombre_usuario=params[:user][:user_name];
     # @email=params[:user][:email];
     # @password=params[:user][:password];

     # @user=User.new({
     # :user_name => @nombre_usuario,
     # :email => @email,
     # :password => @password
     # });

      super
      @estadistica = Estadistica.new({
      :user_id => User.last.id
      });  
      if @estadistica.save()
      end 
      #else
      #  render "/users/sign_up";
      #end
    end
    
  # GET /resource/sign_up


  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

distribuidos/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

distribuidos/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

distribuidos/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if user_signed_in?
			@estadisticas = Estadistica.select("id, clasificacion, victorias, derrotas, empates,user_id").where(:user_id => current_user.id);
		end

		
	end

end

distribuidos/app/helpers/application_helper.rb
module ApplicationHelper
end

distribuidos/app/helpers/descargas_helper.rb
module DescargasHelper
end

distribuidos/app/helpers/estadistica_helper.rb
module EstadisticaHelper
end

distribuidos/app/helpers/welcome_helper.rb
module WelcomeHelper
end

distribuidos/app/views/descargas/index.html.erb
<div class="contp" style="width:30%;margin:0 auto;">
	<h2>Descargas</h2>
	<p>Find me in app/views/descargas/index.html.erb</p>
</div>

distribuidos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Distribuidos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
		<nav class="be-blue white  nav">
			<url class="no-list row	 middle-xs">
				<li class="col-xs-offset-1">
				<h1 class="no-margin" id="logo"><%= image_tag "Bw.png",:class => "img", :title => "Battle Network Chess", :size => "50x50"%>attle Network Chess</h1>
				</li>
				<li class="col-xs-offset-5">
					<%= link_to "Inicio", root_path %>
				</li>
				<% if user_signed_in? %>
					<li class="margen_botones">
						<%= link_to "Perfil", root_path %>
					</li>
					<li class="margen_botones ">
						<%= link_to "Descargas", descargas_index_path %>
					</li>
					<li class="margen_botones ">
					<%= link_to "Cerrar sesión", destroy_user_session_path, :method => :delete%>
					</li>
				<%else%>
					<li class="margen_botones ">
						<%= link_to "Registrarse", new_user_registration_path %>
					</li>
					<li class="margen_botones ">
						<%= link_to "Descargas", descargas_index_path %>
					</li>
					<li class="margen_botones ">
						<%= link_to "Iniciar Sesión", new_user_session_path%>
					</li>
				<%end%>
			</url>
		</nav>	
	</header>
	<% flash.each do |key, value| %>
    	<div class="alert alert-<%= key %> alert-dismissable">
        	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        	<%= value %>
    	</div>
	<% end %>
	<%= yield %>
<div class="footer-probando">
Probando pie de pagina
</div>
</body>
</html>

distribuidos/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

distribuidos/app/views/welcome/index.html.erb
<div style="width:50%;margin:0 auto;">
<% if user_signed_in? %>
<h2 >Usuario <%=current_user.user_name%></h2>
<p>Perfil 
	<p>ID del usuario: <%=current_user.id%></p>
	<p>Nombre de usuario: <%=current_user.user_name%> </p>
	<p>Correo electronico: <%=current_user.email%></p>
	<p>Permisos: <%=current_user.role%></p>
	<p>Estado: <%=current_user.estado%></p>
	<p>Pass: <%=current_user.pass%></p>
</p>
<br/>

<%@estadisticas.each do |estadistica| %>
<p>Estadistica
	<p>Estadistica del usuario: <%= estadistica.user_id %></p>
	<p>Clasificacion: <%= estadistica.clasificacion %></p>
	<p>Victorias:  <%= estadistica.victorias%></p>
	<p>Derrotas: <%=estadistica.derrotas%></p>
	<p>Empates: <%=estadistica.empates%></p>
</p>
<%end%>
<%else%>
<h2  class="text-center text-muted">Historia del ajedrez</h2>

<p>En la historia del ajedrez el origen del juego sigue siendo controvertido, pero la versión más aceptada es que el ajedrez fue inventado en Asia, probablemente en la India, con el nombre de chaturanga y desde allí se extendió a China, Rusia, Persia y Europa, donde se estableció la normativa vigente. Sin embargo, investigaciones recientes indican un posible origen chino, en la región entre Uzbekistán y la antigua Persia, que se podría remontar hasta el siglo III a. C.</p>

<p>Uno de los registros literarios más antiguos sobre el ajedrez es el poema persa Karnamakg-i-Artakhshatr-i-Papakan, escrito en el siglo VI, y, a partir de esta era, su evolución está mejor documentada y ampliamente aceptada en el mundo académico. Tras la conquista de Persia por los árabes, éstos asimilaron el juego y lo difundieron en Occidente, llevándolo al norte de África y Europa, e incluso la actual España e Italia alrededor del siglo X, desde donde se extendió al resto del continente llegando a la región de Escandinavia e Islandia. En Oriente, el ajedrez se ha expandido desde su versión china, el Xiangqi, a Corea y Japón en el siglo X.</p>

<p>En el siglo XV, el juego fue ampliamente difundido en Europa y entre las variantes existentes del juego, la europea fue el que se destacó por la velocidad indicada por la inclusión de la dama y el alfil. A pesar de que en esa época ya existía literatura de ajedrez, fue en este período cuando comenzaron a surgir el primer análisis de aperturas debido a las nuevas posibilidades de juego.</p>

<p>Las partidas comenzaron a ser registrados con mayor frecuencia y se han publicado más estudios teóricos. En el siglo XVIII se fundaron los primeros clubes para la práctica de ajedrez y federaciones deportivas en Europa, y debido a la gran cantidad de pequeños torneos que ocurren por todo el continente, en 1851 se celebró el primer torneo internacional en Londres. La popularidad de las competiciones internacionales ha llevado a la creación del título de campeón del mundo, ganado por Wilhelm Steinitz en 1886, y, en 1924, se fundó la Federación Internacional de Ajedrez (FIDE), en París, que organiza la primera Olimpiada de Ajedrez y el mundial femenino, ganado por Vera Menchik.</p>

<p>A finales de la década de 1950, con la popularización de las computadoras, comenzaron a surgir los primeros programas que juegan al ajedrez, que acompañaban la evolución del tratamiento de la información e introducirían el juego en la era moderna con competiciones on-line y facilitando el análisis de las partidas.</p>
<%end%>

</div>